### ISSUE TITLE
Aeroo Reports not working due to some errors

### ISSUE THREAD

**Issue by ghanshyam2911** [jamotion/aeroo#2]
Hi guys, First of all thank you all for contribute this modules for odoo v8, i installed this module 1 month ago, it worked fine at that time, but due to some changes in odoo repository, now aeroo reports are not working  :(.  i found some errors, like 
1. No module named browse_record_list, 
2. fields.serialized  is not working
please help me,
Thanks.

**Comment by jordg** [comment]
I have managed to get this working on 6.1. This is probably the same solution for V7/8.
1, Recompile Libreoffice as per https://gist.github.com/hbrunn/6f4a007a6ff7f75c0f8b
2, Note exact version installed. In my case: 1:4.3.5~rc2-0ubuntu1~trusty1
2, Download python-uno_4.3.3-2_amd64.deb
3, Follow instructions to repackage above deb https://gist.github.com/shamil/3140558
Change DEBIAN/control
Version: 1:4.3.5~rc2-0ubuntu1~trusty1
Depends: libreoffice-core (= 1:4.3.5~rc2-0ubuntu1~trusty1), .......
4, dpkg-deb -b python-uno python-uno_4.3.5~rc2-0_amd64.deb
5, dpkg -i python-uno_4.3.5~rc2-0_amd64.deb
6, In ~/openerp/.bashrc # Resolve problem 1
Add:
PYTHONPATH=$PYTHONPATH:/usr/lib/libreoffice/program
export PYTHONPATH
7, Enjoy

Please notify if this works for you.

**Comment by rm-jamotion** [comment]
Hi all

Because of the official release of aeroo reports for Odoo 8.0 is available - and after some tests I think it works nice, I will close all Issues here. Please use the official repository of alistek now: https://github.com/aeroo 

Thanks for all your help!
Kind Regards
Renzo
